### ISSUE TITLE
Cannot convert 'const OptixDenoiserOptions*' to 'OptixDenoiserModelKind'

### ISSUE THREAD

**Issue by brugalada** [keithroe/PyOptiX#2]
Hello!

I am trying to install this version of PyOptix following the guidelines by @gmarkall. That is:

>> pip3 install --global-option build --global-option --debug .

The call stops with the error (full output attached):
```
Scanning dependencies of target optix
    [ 50%] Building CXX object CMakeFiles/optix.dir/src/main.cpp.o
    /tmp/pip-req-build-fcoh1vbb/src/main.cpp: In function 'void pyoptix::denoiserCreate(pyoptix::DeviceContext, const OptixDenoiserOptions*, pyoptix::Denoiser*)':
    /tmp/pip-req-build-fcoh1vbb/src/main.cpp:924:13: error: cannot convert 'const OptixDenoiserOptions*' to 'OptixDenoiserModelKind'
      924 |             options,
          |             ^~~~~~~
          |             |
          |             const OptixDenoiserOptions*
```

It might very well be that I am doing something wrong. If that is the case, could you please indicate me how to fix it?

Thank you in advance!

[ErrorLog_PyOptiX_20052021.txt](https://github.com/keithroe/PyOptiX/files/6516063/ErrorLog_PyOptiX_20052021.txt)

**Comment by gmarkall** [comment]
Are you building with OptiX 7.2? If not, can you try with 7.2?

**Comment by brugalada** [comment]
The problem is that I cannot install OptiX myself. I need to ask the HPC administrator to do it for me. In other words, they installed the latest version. I will try to see if they can also put 7.2 and then re-build PyOptiX.

**Comment by gmarkall** [comment]
If it helps, OptiX will build / install into any directory that you specify - it doesn't need to go into a special location in the filesystem. I have it installed in my home dir.

**Comment by gmarkall** [comment]
The latest revision should work with OptiX 7.3.0 (see #3) - can you confirm that it now works for you with 7.3.0?

**Comment by brugalada** [comment]
I managed to install it successfully, no problems. I am now having issues running the example hello.py, but I think it is because of a different reason.

**Comment by gmarkall** [comment]
OK - closing this issue as it seems to be resolved.
